### ISSUE TITLE
Initial sync not working any more

### ISSUE THREAD

**Issue by hawkpatrick** [openshift/jenkins-sync-plugin#392] opened 2021-07-26 16:39 UTC
**Description**
When jenkins starts it does not sync the existing openshift resources. This was the case in OpenShift Sync 1.0.46. 

**Expectation**
During jenkins startup all resources are scanned and matches (having the required label) are addedto jenkins  if not present. 

**First analysis**
The functionality seems to be broken since 1.0.47. The call of the init function is commented out, e.g. for configMaps:

//        ConfigMapList list = getOpenshiftClient().configMaps().inNamespace(namespace).list();
//        onInit(list.getItems());

Is that on purpose? If yes: Is it possible to trigger the sync programmatically?

**Comment by akram** [comment] 2021-07-27 08:06
Hi @hawkpatrick , thank you for reporting this. 
In 1.0.47 we have move to an approach using `SharedInformer` implements of the kubernetes-client library. We noticed then that we receive a full list of existing objects on startup as add events, this is why calls to `onInit` methods have been commented out; as we fallback to the add case.

This was passing our QE tests and we were seeing correct syncs on startup. Can you please share your logs? maybe also by increasing log level for `io.fabric8.kubernetes-client` package?

I am adding @jitendar-singh as this is an interesting QE case.
/assign @jitendar-singh

**Comment by hawkpatrick** [comment] 2021-07-29 16:10
Hi @akram, 

thank you for the investigation. 

Here are the logs you asked for: 
[logAllFabricIo.txt](https://github.com/openshift/jenkins-sync-plugin/files/6901830/logAllFabricIo.txt)

The log output is filtered on "fabric8". If you need more information please let me know.

There is one line which could be a problem: "403=Forbidden!Configured service account doesn't have access" but I'm not sure where this come from and if it's the root cause. 

As mentioned previously: After updating the resources (secret, configmap), e.g. by adding a label, the sync is done and the elements appear on jenkins. 

Here is the log output for what happens when I put a label on the secret: 
[whenUpdatingSecret.txt](https://github.com/openshift/jenkins-sync-plugin/files/6901913/whenUpdatingSecret.txt)

The plugin versions we are using: 

Kubernetes Client API Plugin 5.4.1
Kubernetes 1.30.0	
OpenShift Sync 1.0.48

**Comment by akram** [comment] 2021-10-15 04:48
Can you please update to 1.0.50 ? 
We have fixed some regressions in it since then.

**Comment by hawkpatrick** [comment] 2021-11-05 09:34
> I noticed this same issue when troubleshooting why some credentials were being deleted by the sync plugin v1.0.50, though no one deleted the secret in Openshift (4.7) nor in Jenkins (2.303.2 LTS) itself.
> 
> `2021-10-28 18:36:11 WARNING io.fabric8.kubernetes.client.informers.cache.ReflectorWatcher onClose Watch closing with exception io.fabric8.kubernetes.client.WatcherException: too old resource version: 24701678 (24741295) 2021-10-28 15:05:39 INFO io.fabric8.jenkins.openshiftsync.SecretInformer onDelete Secret informer received delete event for: first-credential 2021-10-28 15:05:39 INFO io.fabric8.jenkins.openshiftsync.CredentialsUtils deleteCredential About to delete credential first-credentialwhich is referenced by jobs: [edit] 2021-10-28 15:05:39 INFO io.fabric8.jenkins.openshiftsync.CredentialsUtils deleteCredential Deleted credential first-credential from Secret NamespaceName{myProject:first-credential} with revision: 24605068 2021-10-28 15:05:39 INFO io.fabric8.jenkins.openshiftsync.SecretInformer onDelete Secret informer received delete event for: second-credential 2021-10-28 15:05:39 INFO io.fabric8.jenkins.openshiftsync.CredentialsUtils deleteCredential About to delete credential second-credentialwhich is referenced by jobs: [edit] 2021-10-28 15:05:40 INFO io.fabric8.jenkins.openshiftsync.CredentialsUtils deleteCredential Deleted credential second-credential from Secret NamespaceName{myProject:second-credential} with revision: 24604998 `

We saw the same problem. Secrets and pod agent templates were randomly disappearing, very annoying. However this problem I believe came from the kubernetes plugin which triggered wrong events. 

We currently are using an ugly workaround script: All resources that have a specific tag (e.g. for secrets it's credential.sync.jenkins.openshift.io=true) will get an update after jenkins startup by setting a random label on them. This will force a sync of the resource to jenkins. Afterwards we disable the openshift sync plugin completely as we do not need the functionality "dynamically adding resources at jenkins runtime". When we add new resources we have to restart the jenkins. But at least we do not have randomly disappearing resources anymore.

**Comment by chrisu001** [comment] 2021-11-14 09:41
Same Problem here with BuildConfigs.
Jenkins: 2.289.2 (ephemeral /var/lib/jenkins)
OpenShift Sync: 1.0.50
Kubernetes:  1.30.1
Kubernetes Client API Plugin. 5.4.1
Openshift: 4.9

Suggestion?:
on jenkins startup, the informer does not loop through all existing ressources (in our case secrets and BCs).
An update (oc apply..) on the resources with dummy-changes triggers the informer and the jenkins jobs (secrets) will be created as expected.

But of course this assumption will not match to @akram comment above:
`In 1.0.47 we have moved to an approach using SharedInformer implemented by kubernetes-client library. We noticed then that we receive a full list of existing objects on startup as add events,`

**Comment by chriscarpenter12** [comment] 2021-11-15 21:41
We're seeing the exact same behavior going from 4.7 jenkins container to 4.8. On start of the Jenkins pod there are no pod template config maps synced. Only the default maven and nodejs pod templates exist. Any edit of the existing config maps triggers a sync event, and the pod templates get added.

Jenkins 2.289.3
OPENSHIFT_BUILD_NAME jenkins-4.8-2
openshift-sync 1.0.50
kubernetes 1.30.1
kubernetes-client-api 5.4.1

This would be breaking for our current workflow as there'd be no labels available on a pod restart.

**Comment by jzr1991** [comment] 2021-11-18 18:51
I'm seeing issues with version 1.0.48 of the sync plugin where secrets are disappearing. Similarly, if I delete the secret in Jenkins I'm sure the secret used to reappear but it no longer does.

The logs aren't helpful but I seem to see a lot of "resource version too old" with a watch closing, though I'm not certain this is the cause

**Comment by adambkaplan** [comment] 2021-11-19 14:52
Filed https://bugzilla.redhat.com/show_bug.cgi?id=2024933 to track this issue.

**Comment by thikade** [comment] 2021-12-22 13:59
saw exactly the same issue using versions: 
Jenkins 2.303.3
openshift-sync 1.0.50

I then tried again using latest openshift-sync plugin v1.0.51 like Priti Kumari did in the aforementioned bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2024933#c5 , and it works again - at least for secrets and buildconfigs, which I am using.

**Closed** 2022-08-20 08:00 UTC
Labels: lifecycle/rotten
