### ISSUE TITLE
Opensshift Jenkins sync plugin triggering two build from single build config in openshift cluster.

### ISSUE THREAD

**Issue by jvinod1985** [openshift/jenkins-sync-plugin#267] opened 2018-10-09 06:10 UTC
I am facing strange issue. When My build run in Opneshift cluster ( on internal jenkins inside openshift cluster). It should trigger on build in external jenkins as per configuration. But it is triggering two build in 
 external jenkins. See the screen shot. Two build are trigger and the triggering cause is same.
Does anyone have idea about such issue related to Jenkins OpenShift sync plugin.

![openshiftsync](https://user-images.githubusercontent.com/29461023/46649688-98ee2e00-cbb7-11e8-85fc-fafb84c0c5a0.JPG)

**Comment by bparees** [comment] 2018-10-09 13:42
What is supposed to trigger the build on your external jenkins?

**Comment by jvinod1985** [comment] 2018-10-09 14:04
Another job on the jenkins inside the openshift cluster triggers my job in external jenkins

**Comment by gabemontero** [comment] 2018-10-09 14:13
How *exactly* does the internal jenkins job trigger the external jenkins job @jvinod1985 ?

Among other things, we have some [restrictions](https://github.com/openshift/jenkins-sync-plugin/#restrictions) on how build can be triggered

**Comment by gabemontero** [comment] 2018-11-24 15:31
Most likely this is a duplicate of https://github.com/openshift/jenkins-sync-plugin/issues/272

We were able to get sufficient details while working that issue to get a fix compiled.

v1.0.30 of this plugin has the fix.  You can pull that version of the bug manually from the jenkins update center and install it, or wait for the openshift jenkins image to get updated with it.

**Closed by gabemontero** 2018-11-24 15:31 UTC
