### ISSUE TITLE
NullPointerException initialising build

### ISSUE THREAD

**Issue by tdcox** [openshift/jenkins-sync-plugin#172] opened 2017-09-14 20:54 UTC
After creating a default Vert.x quickstart using Fabric8 4.0.192 under GKE 1.7.5 (no RBAC, https, domain certs) the build process hangs with a NullPointerException.

Build log:
Branch indexing
17:10:53 Connecting to https://api.github.com using tdcox/****** (cd-github)
Obtained Jenkinsfile from 9ace318dcdc0a6cce5a266880452d661cd406c00
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label launchpad-maven
\<spinning\>

Jenkins log:
https://gist.github.com/tdcox/eb1b11b40435b97072d306d44d990d54

**Comment by gabemontero** [comment] 2017-09-14 21:33
thanks for the report @tdcox 

based on the line numbers and method names in the stack trace, the version of sync plugin is at least a few iteration old;  still if possible I'd like to confirm we addressed your NPE in our later iterations / rewrites.

any chance you know what version of sync plugin is in `Fabric8 4.0.192` ?  I tried some quick searches but came up empty.

@jstrachan @rawlingsj - any pointers on where to look to see what version of sync plugin is used with `Fabric8 4.0.192`

thanks

**Comment by jstrachan** [comment] 2017-09-14 21:36
the issue around `Jenkins doesn’t have label launchpad-maven` was due to a temporary regression in the forge microservice generating invalid pipelines for openshift.io / fabric8 which has since been fixed.

I'll look separately at the NPE stuff; though we're using this fork in fabric8 right now...
https://github.com/fabric8io/jenkins-sync-plugin/tree/job-to-bc

**Comment by gabemontero** [comment] 2017-09-14 21:55
thanks for the info and quick response @jstrachan 

@tdcox - given the using of a separate fork of sync plugin in fabric, I would close this issue and let you and @jstrachan track things in https://github.com/fabric8io/jenkins-sync-plugin, but it it looks like that repo is not taking issues (at least I couldn't see a way to open them when I got there, but it has been a hectic afternoon ;-) )

so we'll leave this open for now - thanks

**Comment by gabemontero** [comment] 2017-10-09 15:18
Ok, looking at some of the module history in https://github.com/fabric8io/jenkins-sync-plugin/tree/job-to-bc

Given this NPE:
```
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.triggerJob(JenkinsUtils.java:113)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.buildAdded(BuildWatcher.java:241)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.eventReceived(BuildWatcher.java:136)
```

Most likely maps to line
```
switch (bcProp.getBuildRunPolicy()) {
```

at least as far back as commit 68608b66689e23fa8debe9273a9a9ca7e4178a81 July 4 of this year.

bcProp can't be null because it is checked for that just prior to the switch, but perhaps the run policy is coming back null (though why that might be the case is a separate cause for concern), and based on which version of Java you are running, switching on null might cause problems.

I'll add the null check in this repo's version.

@jstrachan - if you'd like for me to submit a PR to https://github.com/fabric8io/jenkins-sync-plugin/tree/job-to-bc just say so here.

**Closed** 2017-10-12 20:01 UTC
Labels: bug
